<?php
return [

    'politicasPrivacidad' => 'Privacy Policies',

    'introduccion' => 'INTRODUCTION',
    'text1' => 'The mission of B&G TECHNOLOGIES, S.A. (ILERNUS) is to train and update the employees of your company through the subscription of plans and content packages of interest. We respect your privacy and we want you to know what information we collect about you and what we do with that information. The following Privacy Policy was created to help you to understand how the information you share with B&G TECHNOLOGIES, S.A. (ILERNUS) will be used. This Privacy Policy applies to all information we collect about you. To have your trust is our main concern, and therefore, we observe the following principles to protect your privacy:',
    'text2' => 'We protect your personal information and we will only provide it to third parties: (1) with your consent; (2) when necessary to process your instructions; (3) to the extent reasonably necessary to maintain the functions and functionality of B&G TECHNOLOGIES, S.A. (ILERNUS); (4) when we reasonably consider that it is required by law, in a subpoena or other judicial proceeding; or (5) where necessary to enforce the Terms of Use or to protect the rights, property or safety of B&G TECHNOLOGIES, S.A. (ILERNUS), its Members and Visitors, and the general public.',
    'text3' => 'We have adopted appropriate security measures to protect your information in accordance with industry standards.',
    'text4' => 'HOW TO CONTACT US',
    'text5' => 'If you have any questions about this Privacy Policy, or if you would like to contact B&G TECHNOLOGIES, S.A. (ILERNUS) for any other reason, please send us your message to: soporte@axionti.com, or through the learning platform, using the "Contact Us" link.',
    'text6' => 'INFORMATION WE COLLECT',
    'text7' => 'Registration Information. You do not need to provide us with any personal information to access our website or to view the information that we generally provide on our website. However, we may offer you the opportunity to register with us or join our email marketing list. Although it is not necessary to register to have access to our website, it is necessary to register and create an account with B&G TECHNOLOGIES, S.A. (ILERNUS) to use the Service.',
    'text8' => 'As part of the process to create an account in B&G TECHNOLOGIES, S.A. (ILERNUS) or participating in certain promotions offered by B&G TECHNOLOGIES, S.A. (ILERNUS), such as raffles, competitions, surveys, newsletters, etc., in addition to your email address, you may be asked to share certain information concerning your education and purchase preferences, among others. B&G TECHNOLOGIES, S.A. (ILERNUS) may need this information to get to know you better, to help you understand new services, programs and offers that you may be interested in, and to improve your online experience.',
    'text9' => 'Automatic data collection. You may visit our website and use some of our services anonymously. Whether or not you have registered with us, B&G TECHNOLOGIES, S.A. (ILERNUS) may collect certain personal information for the use of our services. For example, B&G TECHNOLOGIES, S.A. (ILERNUS) may collect information concerning the type of Internet Browser you use, the type of computer or operating system you use, your IP address, the speed of your connection, the domain name of your Internet service provider, the geographic location from which you are accessing our services and/or the website or advertisement from which you connected to our website. When you use a mobile device (such as a tablet or a smartphone) to access our service, we may access, collect, and store on your device and/or remotely save one or more "Device Identifiers" on your device. These Device Identifiers are small data files or logical data structures that are associated or stored on your mobile device in order to uniquely identify your mobile device. Once you have registered with us, we also track and collect information about you including your transactions with us, our affiliates, and others; and the patterns you followed while using our website, such as the pages of the site you visited, searches that you carried out and the time you stayed on our page. If you contact us, we may keep a history of your correspondence.',
    'text10' => 'Cookies. When you visit our website or click on any link that appears on it, or use one or more of our services, we may use a very common technology in the industry called "cookies" which stores certain information on your computer and allows us to customize your experience to align it with your interests and preferences, or simply to facilitate your access to use our services. Most browsers will allow you to remove or block "cookies" from your computer or hard drive or will alert about them when they are activated. Please refer the instructions of your browser for help or to learn more about its functions. Please note that if you block the use of these cookies from your browser, the service may not be used or you may not have access to our website or it may affect the operation of the webpage. By allowing browser settings to accept cookies from our website or The Service, you authorize us to place cookies on your personal computer and/or technological device. However, users of our website and Service may configure their browser to accept or reject all or certain cookies. Please note that if you configure your browser to disable cookies or other technologies, you may not be able to access to certain parts of our website or Service, or that other parts of our Service may not function properly.',

    'text11' => 'Testimonies',
    'text12' => 'B&G TECHNOLOGIES, S.A. (ILERNUS) may publish customer testimonies on our website, which may contain personal information. Once you accept the Terms of Service that apply to the Service, you give your consent to B&G TECHNOLOGIES, S.A. (ILERNUS) to publish any of your testimonies, comments, name and any other representation that comes from you.',

    'text13' => 'HOW WE USE YOUR PERSONAL INFORMATION',
    'text14' => 'We communicate with you through emails, other means available through the Services, including text messages on mobile phones and automatic notifications. Some examples of these communications include: (1) welcome and participation communications: to inform you about the best ways to use our Services, new features, updates about other Members with whom you are connected and their activity, etc.; (2) communications about the service: include the availability of the service, security and other issues regarding the operation of our Services; (3) promotional messages: include email messages and may contain promotional information directly or on behalf of our partners, including business opportunities and information of companies that are hiring. These messages will be sent to you taking into account your information in the profile and your message preferences.',
    'text15' => 'We use information and content of other users and yours to conduct researches and develop our Services to improve our Services in order to provide you and other users and Visitors with a better and more intuitive experience and increase the number of Members and participation in Our Services and help professionals that are looking for economic opportunities.',
    'text16' => 'We customize your experience and the experiences of other people in our Services. For example, we make sure to show you content such as news and presentations relevant to you, your industry or your profession. We also use the member information and content for invitations and messages personalized to the addressee in order to promote our services.',
    'text17' => 'If you provide B&G TECHNOLOGIES, S.A. (ILERNUS) with your personal information, we will take reasonable and appropriate precautions to protect this information. Except as described in this Privacy Policy, B&G TECHNOLOGIES, S.A. (ILERNUS) will not disclose, share, sell or rent personal information collected on our website to third parties for promotional purposes without your consent, unless it is for a specific program, for which you may ask us not to participate. If you request to receive information from our affiliates by selecting this option in the future, we may share your registration information and information about your transactions in our service with the studios and/or our affiliates. If you access to our services through an affiliated version of our website that contains a notice announcing that such information will be shared with that affiliate, which will appear under the name of the affiliated website, any personal or non-personal information will be shared with that particular affiliate website. Any use of this information by B&G TECHNOLOGIES, S.A. (ILERNUS) will be subject to this Privacy Policy, and any use of such information by an affiliate will be subject to this Privacy Policy and the Privacy Policy of the affiliate. In case that B&G TECHNOLOGIES, S.A. (ILERNUS) sells or transfers part or all of its business and/or assets to another organization, such as in a merger and acquisition operation, or in the case of a bankruptcy, dissolution or liquidation, the personal information of our Customers such as name and email address and any other information collected through our website or service, may be one of the items that can be sold or transferred. The resulting purchaser, or the acquiring company, will comply with the commitments assumed in this Privacy Policy. We do not share your credit card account information with affiliate networks or any other third party except the credit card processing service described below.',

    'text18' => 'THIRD PARTIES ADVERTISERS',
    'text19' => 'B&G TECHNOLOGIES, S.A. (ILERNUS) may allow other companies, called ad servers or ad networks, to publish ads from within The Service. These third parties use technology to send, directly to your Browser, the advertisements and hyperlinks that appear in The Service. In these cases, they automatically receive your IP address. They can also use other technologies (such as “cookies”, JavaScript or Internet “headlights”) to measure the effectiveness of your ads and customize them.',
    'text20' => 'B&G TECHNOLOGIES, S.A. (ILERNUS) does not provide any personal information to these third parties without your consent, unless it is for a specific program in which you may ask us to participate. However, take into account that if an advertiser requests B&G TECHNOLOGIES, S.A. (ILERNUS) to publish an ad to a specific audience or segment of the public, and you respond to that announcement, the advertiser could conclude that you fit within the description of the audience they want to reach.',
    'text21' => 'You should consult the privacy policies of these third parties individually. The privacy policy of B&G TECHNOLOGIES, S.A. (ILERNUS) does not apply to, or control the activities of, these third party advertisers or other Internet sites.',

    'text22' => 'SECURITY ',
    'text23' => 'We have implemented security systems designed to protect the personal information you provide in accordance with industry standards. The access to your data in our Services is protected through password. We also offer secure access through the https protocol to the iLernus.com website. In order to protect the data you store on our servers, we also periodically check our system for vulnerabilities and attacks, and we use a secure access tier one data center. However, since the Internet is not a totally secure environment, we can not guarantee the security of all the information you transmit to us. There is no guarantee that information can not be obtained, disclosed, altered or destroyed in violation of any of our physical, technical or management security measures. You have the responsibility to protect the security of your login information. Keep in mind that emails, instant messages and other similar means of communication with other users are not encrypted, and we strongly recommend you not to share confidential information by these means. It contributes to keep your account safe by using a strong password.',
];