<?php
return [
    'politicasPrivacidad' => 'Políticas de Privacidad',

    'introduccion' => 'Introducción',
    'text1' => 'La misión de B&G TECHNOLOGIES, S.A. (ILERNUS) consiste en capacitar y actualizar a los colaboradores de su empresa a través de la suscripción de planes y paquetes de contenidos de interés. Respetamos su privacidad y queremos que sepa qué información recolectamos sobre usted y qué hacemos con esa información. La siguiente política de privacidad fue creada para ayudarlo a entender cómo será usada la información que usted comparte con B&G TECHNOLOGIES, S.A. (ILERNUS). Esta política de privacidad aplica para toda la información que recolectamos sobre usted.
									Contar con su confianza es nuestra principal preocupación, y por tanto, observamos los siguientes principios para proteger su privacidad:',
    'text2' => 'Protegemos su información personal y solo se la proporcionaremos a terceros: (1) con su consentimiento; (2) cuando sea necesario para tramitar sus instrucciones; (3) en la medida razonablemente necesaria para mantener las funciones y funcionalidades de B&G TECHNOLOGIES, S.A. (ILERNUS); (4) cuando consideremos razonablemente que se exige por ley, en una citación u otro procedimiento judicial; o (5) cuando sea necesario para hacer cumplir las condiciones de uso o para proteger los derechos, la propiedad o la seguridad de B&G TECHNOLOGIES, S.A. (ILERNUS), de sus miembros y visitantes, y del público en general.',
    'text3' => 'Hemos adoptado medidas de seguridad adecuadas para proteger su información de acuerdo con los estándares del sector.',

    'text4' => 'Como Contactarnos',
    'text5' => 'Si tiene alguna pregunta sobre esta política de privacidad, o si quisiera ponerse en contacto con B&G TECHNOLOGIES, S.A. (ILERNUS) por alguna otra razón, por favor envíenos su mensaje a: info@ilernus.com, o a través de la plataforma de aprendizaje, utilizando el enlace “Contáctenos”.',
    'text6' => 'Información que Recabamos',
    'text7' => 'Información de registro. No es necesario que usted nos proporcione ningún tipo de información personal para acceder a nuestro sitio web ni para ver la información que proveemos generalmente en nuestro sitio. Sin embargo, podremos ofrecerle la oportunidad de registrarse con nosotros o unirse a nuestra lista de email marketing. A pesar de que no es necesario registrarse para acceder a nuestro sitio web, sí es necesario registrarse y crear una cuenta con B&G TECHNOLOGIES, S.A. (ILERNUS) para utilizar el servicio. Cuando usted crea su cuenta en B&G TECHNOLOGIES, S.A. (ILERNUS), deberá proveer cierta información personal, incluyendo su nombre y apellido, un nombre de usuario, el país donde vive, su número telefónico y una contraseña. En otras ocasiones, puede que también se le pida que nos proporcione información adicional, como su edad, género, y otros datos personales, con el fin de que usted reciba información adicional sobre nuestros servicios.',
    'text8' => 'Como parte del proceso para crear una cuenta en B&G TECHNOLOGIES, S.A. (ILERNUS) o participar en ciertas promociones ofrecidas por B&G TECHNOLOGIES, S.A. (ILERNUS), como rifas, competencias, encuestas, boletines informativos, etc., además del nombre y dirección de su correo electrónico, puede pedírsele que comparta cierta información concerniente a su educación y preferencias de compra, entre otras. B&G TECHNOLOGIES, S.A. (ILERNUS) podría necesitar esta información para conocerlo mejor, ayudarlo a entender nuevos servicios, programas y ofertas en las cuales usted pueda estar interesado, y así mejorar su experiencia online.',
    'text9' => 'Recolección automática de datos. Usted podrá visitar nuestro sitio web y usar algunos de nuestros servicios de manera anónima. Independientemente de que se haya registrado o no con nosotros, B&G TECHNOLOGIES, S.A. (ILERNUS) puede recolectar cierta información personal para el uso de nuestros servicios. Por ejemplo, B&G TECHNOLOGIES, S.A. (ILERNUS) puede recolectar información concerniente al tipo de navegador de Internet que usted usa, el tipo de computadora o sistema operativo, su dirección de IP, la velocidad de su conexión, el nombre del dominio de su proveedor de servicio Internet, la localidad geográfica desde dónde usted está accediendo a nuestros servicios y/o la página web o propaganda desde donde usted se conectó a nuestro sitio web. Cuando usted utiliza un dispositivo móvil (como por ejemplo una tableta o un teléfono inteligente) para acceder a nuestro servicio, podríamos acceder, recopilar, y almacenar en su dispositivo y/o guardar de manera de remota uno o más “Identificadores de Dispositivos” en su equipo. Estos identificadores de dispositivos, son pequeños archivos de datos o estructuras lógicas de datos que se asocian o almacenan en su dispositivo móvil para poder identificar de forma única su dispositivo móvil. Una vez que se haya registrado con nosotros, también rastreamos y recolectamos información sobre usted incluyendo sus transacciones con nosotros, nuestros afiliados, y otros; y los patrones que siguió usted al usar nuestro sitio web, como las páginas del sitio que usted visitó, búsquedas que llevó a cabo y el tiempo que usted permaneció en nuestra página. Si usted nos contacta, podemos guardar un historial de su correspondencia.',
    'text10' => 'Cookies. Cuando usted visita nuestro sitio web o pulsa cualquier hipervínculo que aparece en ella, o usa uno o más de nuestros servicios, podríamos usar una tecnología muy común en la industria llamada “cookies” la cual almacena cierta información en su computadora y que nos permitirá personalizar su experiencia para alinearla con sus intereses y preferencias, o simplemente facilitar su acceso al usar nuestros servicios. La mayoría de los navegadores permitirán que usted elimine o bloquee las “cookies” de su computador o su disco duro o alertará las mismas cuando estas se activen. Por favor refiérase a las instrucciones de su navegador para ayuda o para conocer mejor sus funciones. Por favor tenga en cuenta, que si usted bloquea de su navegador el uso de estas cookies, el servicio no podrá ser utilizado o no podrá acceder a nuestro sitio web o quizás pueda afectar el funcionamiento de la página como tal. Al permitir la configuración del navegador para aceptar cookies de nuestro sitio web o el servicio, usted	nos autoriza a colocar cookies en su computadora personal y/o dispositivo tecnológico. Sin embargo, los usuarios de nuestro sitio web y servicio pueden configurar su navegador para aceptar o rechazar todas o ciertas, cookies. Tenga en cuenta que si configura su navegador para deshabilitar las cookies u otras tecnologías, es posible que no pueda acceder a ciertas partes de nuestro sitio web o servicio, o que otras partes de nuestro servicio no funcionen correctamente.',

    'text11' => 'Testimonios',
    'text12' => 'B&G TECHNOLOGIES, S.A. (ILERNUS) puede publicar testimonios de sus clientes en nuestro sitio web, los cuales pueden contener información personal. Una vez que usted acepta los términos de servicio que aplican al servicio, usted otorga su consentimiento a B&G TECHNOLOGIES, S.A. (ILERNUS) para publicar cualquier testimonio suyo, comentarios, nombre y cualquier otra representación que provenga de usted.	',
    'text13' => 'Cómo Usamos su Información Personal',
    'text14' => 'Nos comunicamos con usted a través de mensajes de correo electrónico, de otros medios disponibles a través de los servicios, incluidos los mensajes de texto en teléfonos móviles y las notificaciones automáticas. Entre algunos ejemplos de estas comunicaciones destacan los siguientes: (1) comunicaciones de bienvenida y de participación: para informarle sobre las mejores maneras de usar nuestros servicios, nuevas funcionalidades, actualizaciones sobre otros miembros con los que estás conectado y su actividad, etc.; (2) comunicaciones sobre el servicio: abarcan la disponibilidad del servicio, la seguridad y otras cuestiones sobre el funcionamiento de nuestros servicios; (3) mensajes promocionales: incluyen mensajes de correo electrónico y pueden contener información promocional directamente o en nombre de nuestros socios, incluidas oportunidades de negocio e información de empresas que están contratando. Estos mensajes se le enviarán teniendo en cuenta su información en el perfil y sus preferencias de mensajes.',
    'text15' => 'Usamos la información y el contenido de otros usuarios y la suya para realizar investigaciones y desarrollar nuestros servicios para mejorarlos a fin de proporcionarle a usted y a otros usuarios y visitantes una mejor experiencia y más intuitiva, aumentar el número de miembros y de participación en nuestros servicios y ayudar a los profesionales que buscan oportunidades económicas.',
    'text16' => 'Personalizamos su experiencia y las experiencias de otras personas en nuestros servicios. Por ejemplo, procuramos mostrarle contenido como noticias y presentaciones relevantes para usted, su sector o su profesión. También utilizamos la información y el contenido de los miembros para invitaciones y mensajes que promuevan nuestros servicios y estén personalizados para el destinatario.',
    'text17' => 'Si usted provee a B&G TECHNOLOGIES, S.A. (ILERNUS) de información personal, tomaremos medidas razonables y apropiadas para proteger esta información. Excepto, conforme está descrito en esta política de privacidad, B&G TECHNOLOGIES, S.A. (ILERNUS) no revelará, compartirá, venderá ni alquilará información personal recolectada en nuestro sitio web a terceros para uso promocional sin su consentimiento, a menos que sea para un programa específico, para el cual podrá pedirnos no participar. Si usted solicita recibir información de nuestros afiliados al seleccionar esta opción en el futuro, podremos compartir su información de registro e información sobre sus transacciones en nuestro servicio con los estudios y/o nuestros afiliados. Si usted accede a nuestros servicios a través de una versión afiliada de nuestro sitio web que contenga un aviso anunciando que esa información será compartida con dicho afiliado, la cual aparecerá bajo el nombre del sitio web afiliado, cualquier información personal o no personal será compartida con dicho sitio web afiliado. Cualquier uso de esa información por parte de B&G TECHNOLOGIES, S.A. (ILERNUS) estará sujeto a esta política de privacidad, y cualquier uso de dicha información por un afiliado estará sujeto a esta política de privacidad y la política de privacidad del afiliado. En caso que B&G TECHNOLOGIES, S.A. (ILERNUS) vendiera o transfiriese parte o la totalidad de sus negocios y/o nuestros activos a otra organización, como por ejemplo en una operación de fusión y adquisición, o en el caso de una quiebra, disolución o liquidación, la información personal de nuestros clientes como el nombre y la dirección de correo electrónico y cualquier otra información recolectada a través de nuestro sitio web o servicio, puede ser uno de los artículos vendidos o transferidos. El comprador resultante, o la sociedad absorbente o adquiriente, cumplirá con los compromisos asumidos en la presente política de privacidad. Nosotros no compartimos la información de sus cuentas de tarjetas de crédito con redes afiliadas ni ningún otro tercero, excepto al servicio de procesamiento de tarjetas de crédito descritos más abajo.',


    'text18' => 'Terceros Anunciantes',
    'text19' => 'B&G TECHNOLOGIES, S.A. (ILERNUS) puede permitir a otras compañías, llamadas servidores de anuncios o redes de anuncios, publicar anuncios desde dentro del servicio. Estos terceros utilizan tecnología para enviar, directamente a su navegador, los anuncios e hipervínculos que aparecen en el servicio. En estos casos, ellos reciben de forma automática la dirección IP de usted. Pueden usar además otras tecnologías (como “cookies,” JavaScript, o “faros” de Internet) para medir la efectividad de sus anuncios y para personalizarlos.',
    'text20' => 'B&G TECHNOLOGIES, S.A. (ILERNUS) no proporciona ninguna información personal a estos terceros sin su consentimiento, a menos que sea para un programa específico en el que podrá pedirnos participar. Sin embargo, tenga en cuenta que si un anunciante pide a B&G TECHNOLOGIES, S.A. (ILERNUS) publicar un anuncio a un público específico o, a un segmento del público, y usted responde a dicho anuncio, el anunciante podría concluir que usted encaja dentro de la descripción del público que quiere alcanzar.',
    'text21' => 'Usted debe consultar individualmente las políticas de privacidad de estos terceros. La política de privacidad de B&G TECHNOLOGIES, S.A. (ILERNUS) no aplica, ni podemos controlar las actividades de estos anunciantes terceros u otros sitios en Internet.',
    'text22' => 'Seguridad',
    'text23' => 'En B&G TECHNOLOGIES, S.A. (ILERNUS) hemos implementado sistemas de seguridad diseñados para proteger la información personal de los usuarios que utilicen nuestro portal. El acceso a sus datos como información personal que ingrese en nuestro sitio web están protegidos mediante una contraseña con un algoritmo de encriptación como el acceso seguro mediante el protocolo https al sitio web de iLernus. Realizamos auditorías continuas para la detección de vulnerabilidad y ataques a nuestro sistema, para ello contamos con una infraestructura en Google Cloud de alta capacidad y acceso seguro.',



];